#!/bin/sh
# Exit when error happens
set -e

echo "Running database migrations..."
npx prisma migrate deploy || {
  echo "Migration failed, attempting to baseline the database"
  
  # Make migrations directory if it doesn't exist
  mkdir -p prisma/migrations/0_baseline
  
  # Create a baseline migration
  echo "-- This is an empty migration that serves as a baseline for an existing database
-- It was auto-generated by the entrypoint script" > prisma/migrations/0_baseline/migration.sql
  
  # Create migration metadata
  echo '{
  "version": "0.3.14-fixed",
  "description": "Baseline existing database",
  "dialect": "postgresql"
}' > prisma/migrations/0_baseline/migration.toml
  
  # Mark the baseline as applied
  npx prisma migrate resolve --applied 0_baseline
  
  # Try running migrations again
  echo "Rerunning migrations after baselining..."
  npx prisma migrate deploy
}

# Start application
npx next start